/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NamedPipe {
  get path(): string
  close(): void
}

export declare class Pipe {
  get fd(): number
  get name(): string
  close(): void
}

export declare function share(payload: Buffer, name?: string | undefined | null): Promise<NamedPipe | Pipe>

export declare function shareFIFO(payload: Buffer, name?: string | undefined | null): Promise<NamedPipe>

export declare function shareMemFD(payload: Buffer, name?: string | undefined | null): Pipe

export declare function shareNamedPipe(payload: Buffer, name?: string | undefined | null): Promise<NamedPipe>

export declare function sharePipe(payload: Buffer, name?: string | undefined | null): Pipe

export declare function shareSHM(payload: Buffer, name?: string | undefined | null): Pipe

export declare function shm_open(name: string, flags: number, mode: number): number
