/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Unix only
 */
export declare class Pipe {
  get fd(): number
  get name(): string
  close(): void
}

/**
 * Windows only
 */
export declare class NamedPipe {
  get path(): string
  close(): void
}

export declare function memfd_create(name: string, flags: number): number

export declare function set_cloexec(fd: number, enabled: boolean): void

export declare function share(payload: Buffer, name?: string | undefined | null): Pipe | NamedPipe

export declare function shareMemFD(payload: Buffer, name?: string | undefined | null): Pipe

export declare function shareSHM(payload: Buffer, name?: string | undefined | null): Pipe

export declare function shm_open(name: string, flags: number, mode: number): number

export declare function shareNamedPipe(name: string): NamedPipe
